import {
  Arc,
  Habit,
  HabitLog,
  Profile,
  Achievement,
  Group,
  HabitType,
  Title,
  Quest,
  BadgeRarity,
  BadgeCategory,
} from "@/types/database";

export interface TemplateDefinition {
  id: string;
  name: string;
  focusArea: string;
  icon: string;
  description: string;
  defaultDurationDays: number;
  habits: Omit<Habit, "id" | "arc_id" | "created_at" | "updated_at">[];
}

export const CHALLENGE_TEMPLATES: TemplateDefinition[] = [
  {
    id: "template-winter-arc",
    name: "Winter Arc 2026",
    focusArea: "Discipline",
    icon: "❄️",
    description: "90 Days of cold discipline, morning focus, physical mastery, and mental resilience.",
    defaultDurationDays: 90,
    habits: [
      {
        name: "🌅 Wake Up at 5:00 AM",
        description: "Rise early with purpose before dawn.",
        icon: "🌅",
        habit_type: "time",
        target_value: 5.0,
        target_unit: "AM",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "04:55:00",
        sort_order: 1,
        is_active: true,
      },
      {
        name: "📵 Mindful Eating (No Phones)",
        description: "No social media or videos while eating meals.",
        icon: "📵",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 2,
        is_active: true,
      },
      {
        name: "🚶 10,000 Steps",
        description: "Daily outdoor walk & physical movement.",
        icon: "🚶",
        habit_type: "number",
        target_value: 10000,
        target_unit: "steps",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "18:00:00",
        sort_order: 3,
        is_active: true,
      },
      {
        name: "🎯 Deep Skill / Coding",
        description: "60 minutes of uninterrupted craft mastery.",
        icon: "🎯",
        habit_type: "duration",
        target_value: 60,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 4,
        is_active: true,
      },
      {
        name: "🍔 Clean Eating (No Junk)",
        description: "Whole food diet. Zero junk food, soda, or ultra-processed sugars.",
        icon: "🍔",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 5,
        is_active: true,
      },
      {
        name: "🚿 Cold Water Discipline",
        description: "Cold shower for mental toughness and dopamine reset.",
        icon: "🚿",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 6,
        is_active: true,
      },
      {
        name: "📖 Book Reading",
        description: "Read philosophy, psychology, or high-value literature.",
        icon: "📖",
        habit_type: "duration",
        target_value: 30,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "21:30:00",
        sort_order: 7,
        is_active: true,
      },
      {
        name: "🌙 Sleep Before 11:00 PM",
        description: "Prioritize circadian rhythm and full recovery.",
        icon: "🌙",
        habit_type: "time",
        target_value: 23.0,
        target_unit: "PM",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "22:30:00",
        sort_order: 8,
        is_active: true,
      },
    ],
  },
  {
    id: "template-study-arc",
    name: "Study Mastery Arc",
    focusArea: "Study",
    icon: "📚",
    description: "60 Days of intellectual immersion, exam preparation, and focused problem solving.",
    defaultDurationDays: 60,
    habits: [
      {
        name: "📚 Deep Focus Study Blocks",
        description: "120 minutes of undistracted subject mastery.",
        icon: "📚",
        habit_type: "duration",
        target_value: 120,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "09:00:00",
        sort_order: 1,
        is_active: true,
      },
      {
        name: "🧩 Solve Practice Problems",
        description: "Complete targeted hard problems or mock questions.",
        icon: "🧩",
        habit_type: "number",
        target_value: 3,
        target_unit: "problems",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 2,
        is_active: true,
      },
      {
        name: "📖 Active Recall / Flashcards",
        description: "Spaced repetition review of core concepts.",
        icon: "📖",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 3,
        is_active: true,
      },
      {
        name: "📵 Zero Social Media during Study",
        description: "Phone locked away in another room during study sessions.",
        icon: "📵",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 4,
        is_active: true,
      },
      {
        name: "🌙 7+ Hours Restorative Sleep",
        description: "Protect memory consolidation and brain plasticity.",
        icon: "🌙",
        habit_type: "duration",
        target_value: 420,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "22:45:00",
        sort_order: 5,
        is_active: true,
      },
    ],
  },
  {
    id: "template-fitness-arc",
    name: "Physical Mastery Arc",
    focusArea: "Fitness",
    icon: "🏋️",
    description: "90 Days of strength, endurance, strict nutrition, and peak body composition.",
    defaultDurationDays: 90,
    habits: [
      {
        name: "🏋️ Strength / Resistance Training",
        description: "Intense weightlifting, calisthenics, or athletic workout.",
        icon: "🏋️",
        habit_type: "duration",
        target_value: 60,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "17:00:00",
        sort_order: 1,
        is_active: true,
      },
      {
        name: "🥩 Hit Daily Protein Target",
        description: "Consume required lean protein for muscle repair.",
        icon: "🥩",
        habit_type: "number",
        target_value: 150,
        target_unit: "grams",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 2,
        is_active: true,
      },
      {
        name: "🚶 10K Daily Steps",
        description: "Base metabolic activity and cardiovascular health.",
        icon: "🚶",
        habit_type: "number",
        target_value: 10000,
        target_unit: "steps",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 3,
        is_active: true,
      },
      {
        name: "💧 Drink 3 Liters of Water",
        description: "Optimal hydration and metabolic function.",
        icon: "💧",
        habit_type: "number",
        target_value: 3,
        target_unit: "liters",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "12:00:00",
        sort_order: 4,
        is_active: true,
      },
      {
        name: "🧘 Mobility & Stretch",
        description: "Flexibility, joint health, and cool-down routines.",
        icon: "🧘",
        habit_type: "duration",
        target_value: 15,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 5,
        is_active: true,
      },
    ],
  },
  {
    id: "template-digital-detox",
    name: "Dopamine Reset Arc",
    focusArea: "Detox",
    icon: "📵",
    description: "30 Days to conquer digital addiction, eliminate doom-scrolling, and reclaim attention.",
    defaultDurationDays: 30,
    habits: [
      {
        name: "📵 Phone-Free First Hour",
        description: "No smartphone usage for first 60 minutes after waking.",
        icon: "📵",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 1,
        is_active: true,
      },
      {
        name: "⏱️ Screen Time Under 2 Hours",
        description: "Strict non-work screen time discipline.",
        icon: "⏱️",
        habit_type: "duration",
        target_value: 120,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 2,
        is_active: true,
      },
      {
        name: "🚶 Nature Walk Without Phone",
        description: "Outdoor walk in silence to reset mental clarity.",
        icon: "🚶",
        habit_type: "duration",
        target_value: 30,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 3,
        is_active: true,
      },
      {
        name: "📖 Read Physical Book",
        description: "High-focus analog reading before bed.",
        icon: "📖",
        habit_type: "duration",
        target_value: 30,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "21:30:00",
        sort_order: 4,
        is_active: true,
      },
    ],
  },
  {
    id: "template-skill-arc",
    name: "Skill Acceleration Arc",
    focusArea: "Skills",
    icon: "🎯",
    description: "60 Days of dedicated deliberate practice on your core craft or career skill.",
    defaultDurationDays: 60,
    habits: [
      {
        name: "🎯 90-Minute Craft Practice",
        description: "High-intensity deliberate practice or code creation.",
        icon: "🎯",
        habit_type: "duration",
        target_value: 90,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: true,
        reminder_time: "10:00:00",
        sort_order: 1,
        is_active: true,
      },
      {
        name: "🛠️ Ship / Commit Daily Code",
        description: "Push real progress to GitHub or live environment.",
        icon: "🛠️",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 2,
        is_active: true,
      },
      {
        name: "📑 Read Documentation / Research",
        description: "Study expert patterns and architectural docs.",
        icon: "📑",
        habit_type: "duration",
        target_value: 30,
        target_unit: "min",
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 3,
        is_active: true,
      },
      {
        name: "📝 Daily Retrospective Journal",
        description: "Log what was learned, bottlenecks, and next actions.",
        icon: "📝",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 4,
        is_active: true,
      },
    ],
  },
  {
    id: "template-custom",
    name: "Custom Arc",
    focusArea: "Custom",
    icon: "✨",
    description: "Build a completely customized challenge tailored to your exact personal mission.",
    defaultDurationDays: 90,
    habits: [
      {
        name: "🎯 Primary Discipline",
        description: "Your highest priority daily commitment.",
        icon: "🎯",
        habit_type: "boolean",
        target_value: null,
        target_unit: null,
        frequency: "daily",
        reminder_enabled: false,
        reminder_time: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
];

export const SEED_ACHIEVEMENTS: Achievement[] = [
  // STREAK BADGES
  {
    id: "ach-1",
    code: "first_step",
    name: "First Step",
    description: "Complete your very first habit in your Arc.",
    icon: "🌱",
    requirement_type: "habits_completed",
    requirement_value: 1,
    xp_reward: 50,
    category: "streak",
    rarity: "common",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-2",
    code: "seven_days",
    name: "7 Days of Fire",
    description: "Maintain an unbroken streak for 7 consecutive days.",
    icon: "🔥",
    requirement_type: "streak_days",
    requirement_value: 7,
    xp_reward: 100,
    category: "streak",
    rarity: "uncommon",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-streak-14",
    code: "fourteen_days",
    name: "14-Day Inferno",
    description: "Hold your discipline line for two consecutive weeks.",
    icon: "⚡",
    requirement_type: "streak_days",
    requirement_value: 14,
    xp_reward: 250,
    category: "streak",
    rarity: "rare",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-4",
    code: "thirty_days",
    name: "30-Day Titan",
    description: "Complete 30 unbroken days of relentless consistency.",
    icon: "🗓️",
    requirement_type: "streak_days",
    requirement_value: 30,
    xp_reward: 500,
    category: "streak",
    rarity: "epic",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-5",
    code: "sixty_days",
    name: "60-Day Ascent",
    description: "Cross two continuous months of committed evolution.",
    icon: "🏔️",
    requirement_type: "streak_days",
    requirement_value: 60,
    xp_reward: 1000,
    category: "streak",
    rarity: "epic",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-6",
    code: "winter_legend",
    name: "90-Day Arc Legend",
    description: "Successfully conquer the complete 90-day Arc journey.",
    icon: "👑",
    requirement_type: "arc_completed",
    requirement_value: 90,
    xp_reward: 2500,
    category: "streak",
    rarity: "mythic",
    created_at: new Date().toISOString(),
  },

  // PERFORMANCE BADGES
  {
    id: "ach-3",
    code: "perfect_day",
    name: "Perfect Day",
    description: "Complete 100% of your daily habits in a single day.",
    icon: "💯",
    requirement_type: "perfect_days",
    requirement_value: 1,
    xp_reward: 100,
    category: "performance",
    rarity: "common",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-perf-triple",
    code: "triple_perfection",
    name: "Triple Perfection",
    description: "Lock in 3 consecutive 100% flawless execution days.",
    icon: "🎯",
    requirement_type: "perfect_days",
    requirement_value: 3,
    xp_reward: 200,
    category: "performance",
    rarity: "uncommon",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-perf-week",
    code: "diamond_week",
    name: "Diamond Week",
    description: "Conquer 7 perfect days in your current Arc.",
    icon: "💎",
    requirement_type: "perfect_days",
    requirement_value: 7,
    xp_reward: 450,
    category: "performance",
    rarity: "rare",
    created_at: new Date().toISOString(),
  },

  // DISCIPLINE BADGES
  {
    id: "ach-7",
    code: "consistency",
    name: "Iron Consistency",
    description: "Complete habits at least 30 times total.",
    icon: "⚔️",
    requirement_type: "habits_completed",
    requirement_value: 30,
    xp_reward: 250,
    category: "discipline",
    rarity: "uncommon",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-disc-century",
    code: "century_habits",
    name: "Century of Discipline",
    description: "Log 100 total completed habits.",
    icon: "🛡️",
    requirement_type: "habits_completed",
    requirement_value: 100,
    xp_reward: 600,
    category: "discipline",
    rarity: "rare",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-disc-unstoppable",
    code: "unstoppable_force",
    name: "Unstoppable Force",
    description: "Conquer 300 total habit executions across all challenges.",
    icon: "🌋",
    requirement_type: "habits_completed",
    requirement_value: 300,
    xp_reward: 1500,
    category: "discipline",
    rarity: "epic",
    created_at: new Date().toISOString(),
  },

  // ARC BADGES
  {
    id: "ach-arc-initiate",
    code: "arc_initiate",
    name: "Arc Initiate",
    description: "Start and establish your first active Arc challenge.",
    icon: "🧭",
    requirement_type: "arc_started",
    requirement_value: 1,
    xp_reward: 100,
    category: "arc",
    rarity: "common",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-arc-winter",
    code: "winter_champion",
    name: "Winter Arc Champion",
    description: "Complete the legendary 90-day Winter Arc template.",
    icon: "❄️",
    requirement_type: "winter_arc_completed",
    requirement_value: 1,
    xp_reward: 2000,
    category: "arc",
    rarity: "epic",
    created_at: new Date().toISOString(),
  },

  // RECOVERY BADGES
  {
    id: "ach-rec-comeback",
    code: "comeback_grit",
    name: "The Comeback",
    description: "Bounce back after a missed day and conquer a 100% day.",
    icon: "🦅",
    requirement_type: "recovery",
    requirement_value: 1,
    xp_reward: 150,
    category: "recovery",
    rarity: "uncommon",
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-rec-resilient",
    code: "iron_resilience",
    name: "Iron Resilience",
    description: "Maintain your focus through 14 days without abandoning your Arc.",
    icon: "🌲",
    requirement_type: "recovery",
    requirement_value: 14,
    xp_reward: 350,
    category: "recovery",
    rarity: "rare",
    created_at: new Date().toISOString(),
  },

  // SECRET ACHIEVEMENTS (HIDDEN UNTIL UNLOCKED)
  {
    id: "ach-sec-midnight",
    code: "midnight_discipline",
    name: "Midnight Discipline",
    description: "Conquer a habit during the midnight hour (12 AM - 3 AM).",
    icon: "🌘",
    requirement_type: "secret_midnight",
    requirement_value: 1,
    xp_reward: 300,
    category: "secret",
    rarity: "rare",
    is_secret: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-sec-warrior",
    code: "weekend_titan",
    name: "Weekend Titan",
    description: "Conquer 100% of habits on both Saturday and Sunday.",
    icon: "🦁",
    requirement_type: "secret_weekend",
    requirement_value: 2,
    xp_reward: 500,
    category: "secret",
    rarity: "epic",
    is_secret: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "ach-sec-centurion",
    code: "the_centurion",
    name: "The Centurion",
    description: "Reach Level 10 and maintain an unbroken 30-day streak.",
    icon: "🌟",
    requirement_type: "secret_centurion",
    requirement_value: 10,
    xp_reward: 1200,
    category: "secret",
    rarity: "mythic",
    is_secret: true,
    created_at: new Date().toISOString(),
  },
];

export const SEED_TITLES: Title[] = [
  {
    id: "title-initiate",
    code: "the_initiate",
    name: "The Initiate",
    description: "Beginner taking their first step into relentless accountability.",
    category: "Progression",
    rarity: "common",
    required_level: 1,
  },
  {
    id: "title-arc-chaser",
    code: "arc_chaser",
    name: "Arc Chaser",
    description: "Dedicated seeker pursuing their next higher version.",
    category: "Identity",
    rarity: "common",
    required_level: 2,
  },
  {
    id: "title-frostborn",
    code: "frostborn",
    name: "Frostborn",
    description: "Tempered by cold discipline and morning focus.",
    category: "Winter Arc",
    rarity: "uncommon",
    required_level: 4,
  },
  {
    id: "title-iron-will",
    code: "iron_will",
    name: "Iron Will",
    description: "Forged in the fires of unbroken weekly execution.",
    category: "Streaks",
    rarity: "rare",
    required_streak: 7,
  },
  {
    id: "title-dawn-breaker",
    code: "dawn_breaker",
    name: "Dawn Breaker",
    description: "Rises before the sun to claim the day before others awake.",
    category: "Discipline",
    rarity: "rare",
    required_level: 7,
  },
  {
    id: "title-relentless",
    code: "relentless",
    name: "Relentless",
    description: "Unbroken month-long commitment with zero excuses.",
    category: "Streaks",
    rarity: "epic",
    required_streak: 30,
  },
  {
    id: "title-winter-legend",
    code: "winter_legend",
    name: "Winter Legend",
    description: "Conqueror of the complete 90-day cold season transformation.",
    category: "Winter Arc",
    rarity: "epic",
    required_achievement_code: "winter_legend",
  },
  {
    id: "title-ascended-mythic",
    code: "ascended_mythic",
    name: "Ascended Titan",
    description: "Master of habits who has reached Level 15 in Arc-Chaser.",
    category: "Prestige",
    rarity: "mythic",
    required_level: 15,
  },
];

export const SEED_QUESTS: Quest[] = [
  {
    id: "quest-daily-habits-3",
    title: "Conquer 3 Habits Today",
    description: "Log at least 3 completed habits today to build momentum.",
    frequency: "daily",
    xp_reward: 50,
    target_count: 3,
    action_type: "complete_habits",
  },
  {
    id: "quest-daily-perfect",
    title: "Flawless Execution (100% Day)",
    description: "Complete all active habits scheduled for today.",
    frequency: "daily",
    xp_reward: 100,
    target_count: 1,
    action_type: "perfect_day",
  },
  {
    id: "quest-daily-early",
    title: "Morning Momentum",
    description: "Log a completed habit before 12:00 PM.",
    frequency: "daily",
    xp_reward: 40,
    target_count: 1,
    action_type: "log_early",
  },
  {
    id: "quest-weekly-streak-5",
    title: "Streak Vanguard",
    description: "Maintain your discipline streak for 5 days this week.",
    frequency: "weekly",
    xp_reward: 200,
    target_count: 5,
    action_type: "streak_day",
  },
  {
    id: "quest-weekly-connect",
    title: "Accountability Ally",
    description: "Connect or send a message to a friend in your circle.",
    frequency: "weekly",
    xp_reward: 120,
    target_count: 1,
    action_type: "send_friend_request",
  },
  {
    id: "quest-weekly-squad",
    title: "Squad Morale",
    description: "Post a message or cheer in your squad chat.",
    frequency: "weekly",
    xp_reward: 150,
    target_count: 1,
    action_type: "cheer_group",
  },
];

export const SEED_FRIENDS: Profile[] = [
  {
    id: "user-arjun-002",
    username: "arjun_k",
    display_name: "Arjun K.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bio: "Day 24 / 90. No excuses, only execution.",
    language: "en",
    timezone: "Asia/Kolkata",
    privacy: "friends",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-sneha-003",
    username: "sneha_r",
    display_name: "Sneha Reddy",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    bio: "Fitness Arc + Study Arc balance.",
    language: "te",
    timezone: "Asia/Kolkata",
    privacy: "friends",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "user-rohit-004",
    username: "rohit_sharma",
    display_name: "Rohit",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    bio: "Digital Detox Arc — Reclaiming dopamine.",
    language: "hi",
    timezone: "Asia/Kolkata",
    privacy: "public",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_GROUPS: Group[] = [
  {
    id: "group-cse-2026",
    owner_id: "user-default-lead",
    name: "CSE Winter Arc 2026",
    description: "Squad of dedicated engineers locked in for 90 days.",
    invite_code: "CSEARC90",
    privacy: "private",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    members_count: 8,
    avg_completion: 82,
    group_streak: 14,
  },
  {
    id: "group-early-birds",
    owner_id: "user-arjun-002",
    name: "5 AM Club & Discipline",
    description: "Wake up early, move, build, conquer.",
    invite_code: "EARLY5AM",
    privacy: "public",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    members_count: 19,
    avg_completion: 78,
    group_streak: 9,
  },
];
